### ISSUE TITLE
InvoiceDetailRequest implementation

### ISSUE THREAD

**Issue by jeromegxj** [mathielen/cxml#28]
Thank you for this library it helped quite a lot!

I'm working with Coupa Punchout implementation and at the end of the Punchout dance it is possible to send the invoice via cXML using an `InvoiceDetailRequest`.
But from what I see it is not implemented in this library, is it normal (in a sense that it's the responsibility of the implementor) or is it something that is just missing (or out of scope)?

Thank you for your help

**Comment by ynnoig** [comment]
Hi, thanks for the question.

We will gladly accept via Pull-Request the implementation of "InvoiceDetailRequest". 
Please feel free to collaborate and together we can add this new feature to the library.

**Comment by jeromegxj** [comment]
Ok so it is a missing part, I'm not sure how I can do it, but I'm going to give it a try :)

**Comment by mathielen** [comment]
Hey @jeromegxj,

do you need help with this?

BG

**Comment by jeromegxj** [comment]
I'll be back someday with the implementation but the project I'm working for is progressing slowly, you can keep this issue close in the meantime
